### ISSUE TITLE
How to test on CIFAR10 dataset?

### ISSUE THREAD

**Issue by Alabenba** [raziehkaviani/rdosr#1]
@raziehkaviani Hi, I am very interested in your research and want to reproduce this project on cifar10 dataset, but it seems that the current codes can not work on it. Could you please provide the scripts that work on cifar10 dataset? It would be very helpful if you could provide it. Thanks a lot.
![image](https://user-images.githubusercontent.com/64249094/99338376-07396a80-28bf-11eb-9c14-3ffc2991bbae.png)

**Comment by raziehkaviani** [comment]
> @raziehkaviani Hi, I am very interested in your research and want to reproduce this project on cifar10 dataset, but it seems that the current codes can not work on it. Could you please provide the scripts that work on cifar10 dataset? It would be very helphul if you could provide it. Thanks a lot.
> ![image](https://user-images.githubusercontent.com/64249094/99338376-07396a80-28bf-11eb-9c14-3ffc2991bbae.png)

Hi,
Thanks for your interest in our work.
I will provide the code for the experiment on Cifar10 in a couple of days and post it here.

**Comment by Alabenba** [comment]
> > @raziehkaviani Hi, I am very interested in your research and want to reproduce this project on cifar10 dataset, but it seems that the current codes can not work on it. Could you please provide the scripts that work on cifar10 dataset? It would be very helphul if you could provide it. Thanks a lot.
> > ![image](https://user-images.githubusercontent.com/64249094/99338376-07396a80-28bf-11eb-9c14-3ffc2991bbae.png)
> 
> Hi,
> Thanks for your interest in our work.
> I will provide the code for the experiment on Cifar10 in a couple of days and post it here.

Thanks for your reply and looking forward to see it as soon as possible.

**Comment by raziehkaviani** [comment]
> > > @raziehkaviani Hi, I am very interested in your research and want to reproduce this project on cifar10 dataset, but it seems that the current codes can not work on it. Could you please provide the scripts that work on cifar10 dataset? It would be very helphul if you could provide it. Thanks a lot.
> > > ![image](https://user-images.githubusercontent.com/64249094/99338376-07396a80-28bf-11eb-9c14-3ffc2991bbae.png)
> > 
> > 
> > Hi,
> > Thanks for your interest in our work.
> > I will provide the code for the experiment on Cifar10 in a couple of days and post it here.
> 
> Thanks for your reply and looking forward to see it as soon as possible.

I uploaded the code for the experiments on RGB data.
The classifier F is substituted with a convolutional classifier written in PyTorch. The Zf obtained from the classifier F is fed to the second component.
Hope it helps.

**Comment by Alabenba** [comment]
> > > > @raziehkaviani Hi, I am very interested in your research and want to reproduce this project on cifar10 dataset, but it seems that the current codes can not work on it. Could you please provide the scripts that work on cifar10 dataset? It would be very helphul if you could provide it. Thanks a lot.
> > > > ![image](https://user-images.githubusercontent.com/64249094/99338376-07396a80-28bf-11eb-9c14-3ffc2991bbae.png)
> > > 
> > > 
> > > Hi,
> > > Thanks for your interest in our work.
> > > I will provide the code for the experiment on Cifar10 in a couple of days and post it here.
> > 
> > 
> > Thanks for your reply and looking forward to see it as soon as possible.
> 
> I uploaded the code for the experiments on RGB data.
> The classifier F is substituted with a convolutional classifier written in PyTorch. The Zf obtained from the classifier F is fed to the second component.
> Hope it helps.
