### ISSUE TITLE
Where did you get B?

### ISSUE THREAD

**Issue by Hengwei-Zhao96** [raziehkaviani/rdosr#2]
Thank you for your outstanding work! But I'm just wondering, where did I get the B for the un-mixing?

**Comment by raziehkaviani** [comment]
> Thank you for your outstanding work! But I'm just wondering, where did I get the B for the un-mixing?

I am glad that you liked our work.
B, which contains bases, is embedded in the weights of the decoder network. You can find it in "rdosr/model_rdosr.py", as "wdecoder".
Hope it helps.
